# Generated by Django 4.0.3 on 2022-03-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Image',
        ),
    ]
