# Generated by Django 4.0.3 on 2022-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_ogimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogimage',
            name='id',
        ),
        migrations.AddField(
            model_name='ogimage',
            name='image_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
